### PR TITLE
New Navbar

### PR DESCRIPTION
**Pull request by jaeko44**
@indykish - The routes need to be re-wired for the new navbar. Other than that, it is functional.

Can you also send me the PSD's (if available) of the icons, so I can change their colour as they don't really match the new navbar. Blue like this looks better.

ss 2016-09-05 at 05 56 08

### CODE REVIEW

**Comment by indykish** [comment]
@jaeko44  I have asked our illustrator. Will get it today. 

I will merge and add the routes.

**Comment by indykish** [comment]
@jaeko44  Did you forget to commit `gnmenu.scss`

**Comment by jaeko44** [comment]
One second will commit @indykish

**Comment by indykish** [comment]
@jaeko44  sure.

**Pull request merged**
