### PR TITLE
Gogs  - api connection issue - need to check- 

### PR DESCRIPTION
**Pull request by morpheyesh**
Yet to work fully.

### CODE REVIEW

**Comment by indykish** [comment]
@morpheyesh Please discuss with @rajthilakmca  on the current_user thing.

@rajthilakmca  Please work with @morpheyesh  and see why there is an issue with current_user. We need to see why this is an issue for yesh. Basically debug to see where the current_user gets loaded.

**Comment by morpheyesh** [comment]
Yes, we need figure out the current_user issue. And no, I don't use the simple_form anymore. I will clean it up once it is all closed.

**Comment by morpheyesh** [comment]
current*

**Comment by morpheyesh** [comment]
I am closing this for now!

**Pull request merged**
