### PR TITLE
billing

### PR DESCRIPTION
**Pull request by jaeko44**
@indykish here's billing, i'll get the rest once done.

### CODE REVIEW

**Comment by indykish** [comment]
@jaeko44  Awesome ! :+1:

**Comment by indykish** [comment]
@jaeko44  Can you clean up  the `public/html/assets` with the files that are only needed ?  This will reduce the `pull-request size`

**Comment by jaeko44** [comment]
All the css needed is in the end of style.css file (that's where I wrote the additional CSS) other than that, we can simply remove public/html complete after the new components are integrated so it's a waste cleaning it up. (Especially since i will be adding the other pages based on the same assets)

**Comment by indykish** [comment]
Alright. Will merge and nuke it once done.

**Comment by indykish** [comment]
@jaeko44    `Cleanup`  i meant is to just commit the file you changed like `component-billing/billing.php` and `css you had changed` in the component-billing directory.

**Pull request merged**
